var shortcutXML = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>WFWorkflowClientVersion</key>
	<string>700</string>
	<key>WFWorkflowClientRelease</key>
	<string>2.0</string>
	<key>WFWorkflowIcon</key>
	<dict>
		<key>WFWorkflowIconStartColor</key>
		<integer>3679049983</integer>
		<key>WFWorkflowIconImageData</key>
		<data></data>
		<key>WFWorkflowIconGlyphNumber</key>
		<integer>59511</integer>
	</dict>
	<key>WFWorkflowImportQuestions</key>
	<array/>
	<key>WFWorkflowActions</key>
	<array>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.openapp</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.appstore</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.searchappstore</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.addnewevent</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.eventattendees</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.calendarevents</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.calendarevents</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.eventattendees</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getupcomingevents</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.removeevents</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.showincalendar</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.adjustdate</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.date</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.format.date</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.date</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gettimebetweendates</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.addnewreminder</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.reminders</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.reminders</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getupcomingreminders</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.removereminders</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.flexibits.fantastical2.addevent</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.flexibits.fantastical2.addreminder</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.flexibits.fantastical2.showinfantastical</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.contacts</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.contacts</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.contacts</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.contacts</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.selectcontacts</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.apple.facetime.facetime</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.email</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.emailaddress</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.selectemail</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.venmo.request</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>IntentAppIdentifier</key>
				<string>com.apple.PassKit.PassKitIntentsExtension</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.venmo.pay</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>IntentAppIdentifier</key>
				<string>com.apple.PassKit.PassKitIntentsExtension</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.apple.mobilephone.call</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.phonenumber</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.phonenumber</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.selectphone</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.skype.skype.call</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.unzip</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.makezip</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.apple.iBooks.openin</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.avairyeditphoto</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.file.append</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.file.createfolder</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.file.delete</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.documentpicker.open</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.file.getlink</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.documentpicker.save</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.files</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.format.filesize</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.files</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.openin</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.previewdocument</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.makepdf</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.print</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.shinyfrog.bear-IOS.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.shinyfrog.bear-IOS.create</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.shinyfrog.bear-IOS.grab</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.shinyfrog.bear-IOS.contents</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.shinyfrog.bear-IOS.open</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.shinyfrog.bear-IOS.search</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.agiletortoise.Drafts4.addto</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.agiletortoise.Drafts4.get</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.agiletortoise.Drafts4.open</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.agiletortoise.Drafts4.runAction</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.evernote.append</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.evernote.new</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.evernote.delete</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.evernote.getlink</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.evernote.get</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.goodreader.open</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.soulmen.ulysses.pad.insert</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.soulmen.ulysses.pad.attach</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.ulysses.sheet</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.soulmen.ulysses.pad.read-sheet</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.soulmen.ulysses.pad.new-group</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.soulmen.ulysses.pad.new-sheet</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.soulmen.ulysses.pad.open</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.health.quantity</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.health.quantity</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.health.quantity.log</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.health.workout.log</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.runscene</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.locations</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getcurrentlocation</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.locations</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.address</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getdistance</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gethalfwaypoint</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getmapslink</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gettraveltime</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.searchlocalbusinesses</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getdirections</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.searchmaps</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.address</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.showinblindsquare</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.itunesartist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.itunesstore</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.searchitunes</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.showinstore</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.addtoplaylist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.addmusictoupnext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.clearupnext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.createplaylist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.music</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getcurrentsong</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.music</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.get.playlist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.playmusic</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.exportsong</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.pausemusic</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvolume</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.skipback</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.skipforward</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.recordaudio</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.takephoto</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.takevideo</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.image.combine</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.image.crop</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.image.flip</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.avairyeditphoto</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.image.mask</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.overlayimageonimage</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.image.resize</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.image.rotate</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.addframetogif</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getframesfromimage</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.makegif</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.makevideofromgif</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.image.convert</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.images</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.images</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.images</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.deletephotos</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.photos</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getlatestbursts</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getlatestlivephotos</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getlastphoto</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getlastscreenshot</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getlastvideo</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.savetocameraroll</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.selectphoto</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.encodemedia</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.trimvideo</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.imgur.upload</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setclipboard</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getclipboard</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.sendemail</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.sendmessage</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>IntentAppIdentifier</key>
				<string>com.apple.MobileSMS</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.apple.mobilenotes.SharingExtension</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.apple.mobileslideshow.StreamShareService</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.airdropdocument</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.share</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.runextension</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.postonfacebook</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.burbn.instagram.openin</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.tapbots.Tweetbot.opentweetbot</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.tapbots.Tweetbot.searchtext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.tapbots.Tweetbot.tweet</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.tapbots.Tweetbot.viewprofile</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.tweet</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.whatsapp.WhatsApp.send</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>net.whatsapp.WhatsApp.openin</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.wordpress.post</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detectlanguage</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.dictatetext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.generatebarcode</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getnameofemoji</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.text</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.scanbarcode</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.showdefinition</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.speaktext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gettext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.text.translate</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.gethtmlfromrichtext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getmarkdownfromrichtext</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getrichtextfromhtml</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getrichtextfrommarkdown</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.text.changecase</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.text.combine</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.correctspelling</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.text.match.getgroup</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.text.match</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.text.replace</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.text.split</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.guidedways.2Do.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.boonbits.captio.appendtonote</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.boonbits.captio.sendnote</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.realmacsoftware.clear.createlist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.realmacsoftware.clear.createtask</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.dayonelog.dayoneiphone.post</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.phocusllp.due.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.outerspaceapps.itranslate.translate</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.omnigroup.OmniFocus2.iPhone.newitem</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.omnigroup.OmniFocus2.iPhone.pastetaskpaper</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.potionfactory.TheHitListMobile.tasks</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.culturedcode.ThingsTouch.addtask</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.todoist.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.trello.add.card</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.trello.add.board</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.trello.add.list</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.trello</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.trello.get</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.wunderlist.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.filter.articles</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.articles</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getarticle</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.giphy</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.readinglist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getwebpagecontents</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.properties.safariwebpage</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.openurl</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.runjavascriptonwebpage</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.searchweb</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.showwebpage</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.url.expand</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.geturlcomponent</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.downloadurl</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.url.getheaders</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.rss</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.rss.extract</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.link</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.url</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>squibner.AmazonLinker.convert</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>squibner.AmazonLinker.search</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.squibner.Blink.convert</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>squibner.AmazonLinker.search</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.squibner.Blink.convert</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.squibner.Blink.search</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.google.chrome.ios.openurl</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.cloudapp.upload</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.instapaper.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.instapaper.get</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.tijo.opener.Opener.show-options</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>fm.overcast.overcast.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.pinboard.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.pinboard.get</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.pocket.add</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.pocket.get</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.venmo.request</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>IntentAppIdentifier</key>
				<string>com.lydia-app</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.venmo.pay</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>IntentAppIdentifier</key>
				<string>com.lydia-app</string>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.burbn.instagram.openin</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.postonfacebook</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.useractivity.open</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>AppBundleIdentifier</key>
				<string>com.apple.weather</string>
				<key>UserActivityData</key>
				<data>YnBsaXN0MDDUAQIDBAUGYWJYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoK4HCDk/RUZHS1BTWFlaXVUkbnVsbN8QGAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyMjJicnIyojIyMuLzAxIzMnIzYjJ1xyZXF1aXJlZEtleXNVdGl0bGVad2VicGFnZVVSTF8QE2R5bmFtaWNBY3Rpdml0eVR5cGVfEBRwZXJzaXN0ZW50SWRlbnRpZmllcldvcHRpb25zXxAZZWxpZ2libGVGb3JQdWJsaWNJbmRleGluZ18QFWVsaWdpYmxlRm9yUHJlZGljdGlvbl5leHBpcmF0aW9uRGF0ZVYkY2xhc3NccGF5bG9hZEVycm9yVHV1aWRYa2V5d29yZHNcYWN0aXZpdHlUeXBlXxASZWxpZ2libGVGb3JIYW5kb2ZmV3ZlcnNpb25fEBdjb250ZW50QXR0cmlidXRlU2V0RGF0YV50ZWFtSWRlbnRpZmllclR0eXBlXxAUZWxpZ2libGVGb3JSZW1pbmRlcnNbcmVmZXJyZXJVUkxXcGF5bG9hZF1jb250ZW50QWN0aW9uXxARZWxpZ2libGVGb3JTZWFyY2iACYAEgACAAIAAgAIICIAAgA2AAIAAgACABQkQAYAGgAAQAQiAAIAIgAAI0zo7Ejw9PldOUy5rZXlzWk5TLm9iamVjdHOgoIAD0kBBQkNaJGNsYXNzbmFtZVgkY2xhc3Nlc1xOU0RpY3Rpb25hcnmiQkRYTlNPYmplY3RfEBRTaG93IHdlYXRoZXIgaW4gTHlvbl8QHmNvbS5hcHBsZS53ZWF0aGVyLnVzZXJhY3Rpdml0edJIEklKV05TLmRhdGFPEQG0YnBsaXN0MDDUAQIDBAUGFRZYJHZlcnNpb25YJG9iamVjdHNZJGFyY2hpdmVyVCR0b3ASAAGGoKQHCA0OVSRudWxs0gkKCwxZY29udGFpbmVyViRjbGFzc4ACgANPEITeugABAACEAAAAAAAAAB0AAADwhAAAAAAAhAAAAGMAAAAEAFMAAAAlAAAAX19jbGFzczpDU1NlYXJjaGFibGVJdGVtQXR0cmlidXRlU2V0AAwAAAAAAAwAAAABAAAAAAAMAAAAAAAMAAAAAQAAAAAAJwAAAPQAAAAA4lAAAADxYAAAAPHSDxARElokY2xhc3NuYW1lWCRjbGFzc2VzXxAcQ1NTZWFyY2hhYmxlSXRlbUF0dHJpYnV0ZVNldKITFF8QHENTU2VhcmNoYWJsZUl0ZW1BdHRyaWJ1dGVTZXRYTlNPYmplY3RfEA9OU0tleWVkQXJjaGl2ZXLRFxhUcm9vdIABAAgAEQAaACMALQAyADcAPABCAEcAUQBYAFoAXADjAOgA8wD8ARsBHgE9AUYBWAFbAWAAAAAAAAACAQAAAAAAAAAZAAAAAAAAAAAAAAAAAAABYoAH0kBBTE1dTlNNdXRhYmxlRGF0YaNOT0RdTlNNdXRhYmxlRGF0YVZOU0RhdGHSSBJRSk8QMU1QAwWCq2Rlc3RWaWV3S2V5rmNpdHlEZXRhaWxWaWV3q2NpdHlOYW1lS2V5pEx5b26AB9I7ElRXolVWgAqAC4AMW2Rlc3RWaWV3S2V5W2NpdHlOYW1lS2V50kBBW1xVTlNTZXSiW0TSQEFeX18QElVBVXNlckFjdGl2aXR5SW5mb6JgRF8QElVBVXNlckFjdGl2aXR5SW5mb18QD05TS2V5ZWRBcmNoaXZlctFjZFRyb290gAEACAARABoAIwAtADIANwBGAEwAfwCMAJIAnQCzAMoA0gDuAQYBFQEcASkBLgE3AUQBWQFhAXsBigGPAaYBsgG6AcgB3AHeAeAB4gHkAeYB6AHpAeoB7AHuAfAB8gH0AfYB9wH5AfsB/QH/AgACAgIEAgYCBwIOAhYCIQIiAiMCJQIqAjUCPgJLAk4CVwJuAo8ClAKcBFQEVgRbBGkEbQR7BIIEhwS7BL0EwgTFBMcEyQTLBNcE4wToBO4E8QT2BQsFDgUjBTUFOAU9AAAAAAAAAgEAAAAAAAAAZQAAAAAAAAAAAAAAAAAABT8=</data>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.comment</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.showresult</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.count</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getitemname</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getitemtype</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.nothing</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setitemname</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.viewresult</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.choosefrommenu</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>A8670784-AE89-4997-A595-F6950860525F</string>
				<key>WFControlFlowMode</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.choosefrommenu</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFMenuItemTitle</key>
				<string>One</string>
				<key>GroupingIdentifier</key>
				<string>A8670784-AE89-4997-A595-F6950860525F</string>
				<key>WFControlFlowMode</key>
				<integer>1</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.choosefrommenu</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>WFMenuItemTitle</key>
				<string>Two</string>
				<key>GroupingIdentifier</key>
				<string>A8670784-AE89-4997-A595-F6950860525F</string>
				<key>WFControlFlowMode</key>
				<integer>1</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.choosefrommenu</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>A8670784-AE89-4997-A595-F6950860525F</string>
				<key>WFControlFlowMode</key>
				<integer>2</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.handoff</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.exit</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.conditional</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>29986165-85FF-4FA9-9CAA-3ACD058A36B6</string>
				<key>WFControlFlowMode</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.conditional</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>29986165-85FF-4FA9-9CAA-3ACD058A36B6</string>
				<key>WFControlFlowMode</key>
				<integer>1</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.conditional</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>29986165-85FF-4FA9-9CAA-3ACD058A36B6</string>
				<key>WFControlFlowMode</key>
				<integer>2</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.repeat.count</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>BB82995D-66C9-4EEA-BC0A-12314C2DB46D</string>
				<key>WFControlFlowMode</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.repeat.count</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>BB82995D-66C9-4EEA-BC0A-12314C2DB46D</string>
				<key>WFControlFlowMode</key>
				<integer>2</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.repeat.each</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>B6B16196-4826-4115-AF61-287D5CFE0152</string>
				<key>WFControlFlowMode</key>
				<integer>0</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.repeat.each</string>
			<key>WFWorkflowActionParameters</key>
			<dict>
				<key>GroupingIdentifier</key>
				<string>B6B16196-4826-4115-AF61-287D5CFE0152</string>
				<key>WFControlFlowMode</key>
				<integer>2</integer>
			</dict>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.delay</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.waittoreturn</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getbatterylevel</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getipaddress</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getdevicedetails</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getwifi</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.airplanemode.set</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.bluetooth.set</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setbrightness</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.cellulardata.set</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.dnd.set</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.flashlight</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.lowpowermode.set</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvolume</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.wifi.set</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.dictionary</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.detect.dictionary</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getvalueforkey</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvalueforkey</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.base64encode</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.hash</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.choosefromlist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getitemfromlist</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.list</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.math</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.statistics</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.format.number</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.number</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.number.random</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.round</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.ask</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.playsound</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.alert</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.notification</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.vibrate</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.runsshscript</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getmyworkflows</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.runworkflow</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.appendvariable</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.getvariable</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.setvariable</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.openxcallbackurl</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>is.workflow.actions.urlencode</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.omz-software.Editorial.runworkflow</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.omz-software.Pythonista.editscript</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.omz-software.Pythonista.runscript</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.agiletortoise.Tally2.get</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
		<dict>
			<key>WFWorkflowActionIdentifier</key>
			<string>com.agiletortoise.Tally2.updatetally</string>
			<key>WFWorkflowActionParameters</key>
			<dict/>
		</dict>
	</array>
	<key>WFWorkflowTypes</key>
	<array>
		<string>NCWidget</string>
		<string>WatchKit</string>
	</array>
	<key>WFWorkflowInputContentItemClasses</key>
	<array>
		<string>WFAppStoreAppContentItem</string>
		<string>WFArticleContentItem</string>
		<string>WFContactContentItem</string>
		<string>WFDateContentItem</string>
		<string>WFEmailAddressContentItem</string>
		<string>WFGenericFileContentItem</string>
		<string>WFImageContentItem</string>
		<string>WFiTunesProductContentItem</string>
		<string>WFLocationContentItem</string>
		<string>WFDCMapsLinkContentItem</string>
		<string>WFAVAssetContentItem</string>
		<string>WFPDFContentItem</string>
		<string>WFPhoneNumberContentItem</string>
		<string>WFRichTextContentItem</string>
		<string>WFSafariWebPageContentItem</string>
		<string>WFStringContentItem</string>
		<string>WFURLContentItem</string>
	</array>
</dict>
</plist>`;

var nodeDictionnary = {
	"gettext" : "Text",
	"downloadurl" : "Get Contents of URL",
	"showresult" : "Show Result",
	"ask" : "Ask for Input",
	"setvariable" : "Set Variable",
	"getitemfromlist" : "Get Item from List",
	"number" : "Number",
	"math" : "Calculate",
	"text.replace" : "Replace Text",
	"text.split" : "Split Text",
	"detect.dictionary" : "Get Dictionary from Input"
};

parseXML(shortcutXML);

function parseXML(xml) {
  	parser = new DOMParser();
  	xmlDoc = parser.parseFromString(shortcutXML,"text/xml");
  	console.log(xmlDoc);
  	var object = organize(xmlDoc);

  	var actions = object.WFWorkflowActions;
  	var importQuestions = object.WFWorkflowImportQuestions;

  	for(var act in actions) {
  		console.log('Action : ', actions[act]);
  		createNode(actions[act]);
  	}
}

function organize(xmlDoc) {
	var nodes = xmlDoc.documentElement.childNodes;
	var object = {};

	//console.log(nodes[1].childNodes[1].innerHTML);

	for(var i = 0; i < nodes.length; i++) {
		var node = nodes[i];
		if(node.nodeName !== "#text"){
			var children = getChildren(node);
			console.log('CHILDREN', children);
		}
	}

	return children;
}

function getChildren(node) {
	var result = {};
	var curKey = null;
	var childNodes = node.childNodes;
	var keySet = false;

	var idx = 0;

	if(childNodes.length > 0) {
		for(var j = 0; j < childNodes.length; j++) {
			var child = childNodes[j];
			if(child.nodeName !== "#text"){
				if(child.nodeName == 'key'){
					keySet = true;
					curKey = child.innerHTML;
					result[curKey] = null;
				} else {
					if(child.nodeName == 'string' || child.nodeName == 'integer') {
						result[curKey] = child.innerHTML;
					} else if(child.nodeName == 'array' || child.nodeName == 'dict'){
						if(keySet){
							result[curKey] = getChildren(child);
							keySet = false;
						}
						else {
							result[child.nodeName + idx] = getChildren(child);
							idx ++;
						}
					}
				}
			}
		}
	}

	return result;
}

function createNode(action) {
	var container = document.getElementById('container');

	var keys = Object.keys(action.WFWorkflowActionParameters);
	var content = [];
	console.log(keys);

	for(var i = 0; i < keys.length; i++) {
		if(keys[i] !== 'UUID') {
			if(keys[i] == "WFTextActionText") {
				var t = document.createElement('p');
				t.innerHTML = action.WFWorkflowActionParameters.WFTextActionText;
				content.push(t);
			} else if(keys[i] == "WFNumberActionNumber") {
				var n = document.createElement('p');
				n.innerHTML = "Number";
				n.classList.add('left');
				content.push(n);
				var v = document.createElement('p');
				if(action.WFWorkflowActionParameters.WFNumberActionNumber.Value.Type == "Variable") {
					v.innerHTML = action.WFWorkflowActionParameters.WFNumberActionNumber.Value.VariableName;
					v.classList.add('variable');
				}
				v.classList.add('right');
				content.push(v);
			} else if(keys[i] == "WFVariableName") {
				var n = document.createElement('p');
				n.innerHTML = "Variable";
				n.classList.add('left');
				content.push(n);
				var v = document.createElement('p');
				v.innerHTML = action.WFWorkflowActionParameters.WFVariableName;
				v.classList.add('variable');
				v.classList.add('right');
				content.push(v);
			}
		}
	}

	var node = document.createElement('div');
	node.classList.add('node');
	container.appendChild(node);

	var nodeTop = document.createElement('div');
	nodeTop.classList.add('nodeTop');
	node.appendChild(nodeTop);

	var nodeTitle = document.createElement('p');
	nodeTitle.classList.add('nodeTitle');
	var nodeUglyTitle = action.WFWorkflowActionIdentifier.replace("is.workflow.actions.", "");
	var title = nodeDictionnary[nodeUglyTitle];
	if(!title){
		title = nodeUglyTitle;
	}
	nodeTitle.innerHTML = title;
	nodeTop.appendChild(nodeTitle);

	if(content.length > 0) {
		var nodeContent = document.createElement('div');
		nodeContent.classList.add('nodeContent');

		for(var j = 0; j < content.length; j++) {
			nodeContent.appendChild(content[j]);
		}

		node.appendChild(nodeContent);
	} else {
		node.classList.add('small');
		nodeTop.classList.add('small');
	}

	
}
 
